### ISSUE TITLE
Auth Gaurd

### ISSUE THREAD

**Issue by sallyg1** [loonix/capacitor-oauth2-azure-example#7]
Hi , 

My tech stack is Ionic angular , latest ionic 6. I am trying to build login screen. The identity provider that I am using for login is Azure AD B2C. 
Thank you for the code example, using it I am able to login and authenticate but how do I create auth guard to protect internal pages ? can you help ?

**Comment by loonix** [comment]
It's great that this is still working, it's been a long time since I developed with ionic. I'll try to find an example and will send it here

**Comment by loonix** [comment]
Sorry it's been really a while and I don't have any examples to help you. Maybe on the official plugin GitHub page you can find better support for it?
