### ISSUE TITLE
Navigation is unreachable warning 

### ISSUE THREAD

**Issue by ananthakrish98** [loonix/capacitor-oauth2-azure-example#8]
**Expected behavior**
it should navigate back to mobile app and give response of the account details
![screenshot](https://user-images.githubusercontent.com/29348917/189313051-9b14ec3a-cff9-4027-b972-d0c37e298424.PNG)

**Comment by loonix** [comment]
Hey, it's been quite a while since I used ionic. I have no idea if this still works. Maybe on the official plugin GitHub page you can find better support for it?

**Comment by loonix** [comment]
Hey, it's been quite a while since I used ionic. I have no idea if this still works. Maybe on the official plugin GitHub page you can find better support for it?
